# Generated by Django 2.0.4 on 2018-04-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content2',
        ),
    ]
