# Generated by Django 2.0.4 on 2018-04-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content2',
            field=models.TextField(null=True),
        ),
    ]
