# Generated by Django 2.0.4 on 2018-04-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180426_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content2',
        ),
    ]
