# Generated by Django 2.0.4 on 2018-04-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(null=True),
        ),
    ]
